### ISSUE TITLE
Please fix metadata

### ISSUE THREAD

**Issue by pcav** [RiaJ16/h-tech_cloud#5]
the description should be also in English, to allow more users to understand plugin usefulness.
links to the repo and bugtracker are wrong.
link to home page is too generic, please use a page especially dedicated to the plugin. if nothing better is available, a link to this repo README would do.

Thanks.

**Comment by RiaJ16** [comment]
I've fixed it, I hope it complies now.
Thanks

Jair

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
